name: inbound_booking
description: Expect Distribution Inbound Booking Diary
publish_to: "none"

version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.5.6
  dropdown_button2: ^2.3.9
  file_picker: ^8.0.0
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/